name: changelog
version: 0.1.0.0

dependencies:
  - base

executables:
  changelog:
    main: changelog.hs
    dependencies:
      - aeson
      - base
      - bytestring
      - directory
      - filepath
      - yaml
